# Configuration path for cloned repositories

development:
  repositories_path: <%= "#{Rails.root}/repositories" %>
  faye_server: 'http://127.0.0.1:9292/faye'
  default_branch: 'develop'
  ssh_agent_script: ''
  ssh_public_key: "/Users/theodelaune/.ssh/id_rsa.pub"
  ssh_private_key: "/Users/theodelaune/.ssh/id_rsa"

production:
  repositories_path: "/var/www/pbtd/shared/repositories"
  faye_server: 'http://127.0.0.1:9292/faye'
  default_branch: 'develop'
  ssh_agent_script: <%= ". #{Rails.root}/lib/pbtd/enable-ssh.sh > /dev/null" %>
  basic_auth_password: 'g1tPbtdT0ol'

staging:
  repositories_path: "/var/www/pbtd/shared/repositories"
  faye_server: 'http://127.0.0.1:9292/faye'
  default_branch: 'develop'
  ssh_agent_script: <%= ". #{Rails.root}/lib/pbtd/enable-ssh.sh > /dev/null" %>
  ssh_public_key: "/var/www/pbtd/shared/tmp/ssh/pbtd_key.pub"
  ssh_private_key: "/var/www/pbtd/shared/tmp/ssh/pbtd_key"
  basic_auth_user: 'synbioz'
  basic_auth_password: 'g1tPbtdT0ol'

test:
  repositories_path: <%= "#{Rails.root}/spec/support/repositories" %>
  faye_server: 'http://127.0.0.1:9292/faye'
  default_branch: 'develop'
  ssh_agent_script: ''
