# Configuration path for cloned repositories

development:
  repositories_path: <%= "#{Rails.root}/repositories" %>
  faye_server: 'http://0.0.0.0:8000/faye'
  default_branch: 'develop'

production:
  repositories_path: "/var/www/pbtd/shared/repositories"
  faye_server: 'http://0.0.0.0:8000/faye'
  default_branch: 'develop'

test:
  repositories_path: <%= "#{Rails.root}/spec/support/repositories" %>
  faye_server: 'http://0.0.0.0:9292/faye'
  default_branch: 'develop'
